server:
  port: 8888
  servlet:
    context-path: /sbs

spring:
  # 开发环境配置
  profiles:
    active: dev

  # 数据库库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbs?serverTimezone=Hongkong&useSSL=false&characterEncoding=utf-8
    username: root
    password: 991010

    # druid 配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 5
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        profile-enable: true
      max-active: 20
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: show status like '%Service_Status%';
      filters: stat,wall
      max-wait: 60000
      filter:
        stat:
          db-type: mysql
          slow-sql-millis: 1000
          log-slow-sql: true
        wall:
          db-type: mysql
          config:
            multi-statement-allow: true
          enabled: true
      test-on-borrow: false
      stat-view-servlet:
        login-password: admin
        login-username: admin
      pool-prepared-statements: true
      initial-size: 5
      min-evictable-idle-time-millis: 300000
      test-on-return: false

  # 文件上传设置
  servlet:
    multipart:
      max-request-size: 57232395
      max-file-size: 57232395
      location:
      file-size-threshold: 0
      enabled: true
      resolve-lazily: false

  # jackson序列化配置
  jackson:
    serialization:
      indent-output: true
    default-property-inclusion: non_null
    generator:
      escape-non-ascii: true

#邮件发送配置
#  spring.mail.default-encoding=UTF-8
#  spring.mail.host=smtp.qq.com
#  spring.mail.username=你的邮箱
#  spring.mail.password=邮箱授权码
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true

  #邮件发送配置
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 2337736075@qq.com
    password: waookefyjkxudije
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # redis 配置
#  redis:
#    password:
#    database: 0
#    port: 6379
#    host: localhost
#    lettuce:
#      pool:
#        max-idle: 500
#        min-idle: 50
#        max-active: 1000
#        max-wait: 2000
#    timeout: 3000

# mybatis 配置
pagehelper:
  supportMethodsArguments: true
  reasonable: true
  helperDialect: mysql
  params: count=countSql

# mybatis 配置
mybatis:
  configuration:
    aggressive-lazy-loading: false
  mapperLocations: classpath:mapper/*.xml

mapper:
  identity: MYSQL
  not-empty: false
  mappers: tk.mybatis.mapper.common.Mapper

# log 日志打印
logging:
  config: classpath:logback-spring.xml

# 文件上传路径
sbs:
  fileup:
    root-path:


